import re

ECONOMIC_KEYWORDS = [
    r"\beconom(y|ic|ies)\b",
    r"\bfinanc(e|ial)\b",
    r"\bmarket(s)?\b",
    r"\bstock(s)?\b",
    r"\bbond(s)?\b",
    r"\bforex\b",
    r"\bcurrency\b",
    r"\bcryptocurrenc(y|ies)\b",
    r"\bbitcoin\b",
    r"\beth(ereum|)\b",
    r"\btrading\b",
    r"\binvest(ing|ment|or)?\b",
    r"\binflat(ion|e)\b",
    r"\bgdp\b",
    r"\bgrowth\b",
    r"\brecess(ion|ive)\b",
    r"\brate(s)?\b",
    r"\binterest\b",
    r"\bfed(eral)?\b",
    r"\bcentral bank\b",
    r"\btariff(s)?\b",
    r"\bsanction(s)?\b",
    r"\bcommodit(y|ies)\b",
    r"\boil\b",
    r"\bgold\b",
    r"\bsilver\b",
    r"\bblockchain\b",
    r"\bdebt\b",
    r"\bdeficit\b",
    r"\btax(es|ation)?\b",
    r"\bbudget\b",
    r"\bpolic(y|ies)\b",
    r"\bregulat(e|ion|ory)\b",
    r"\bderegulat(e|ion)\b",
    r"\btrade\b",
    r"\bimport(s)?\b",
    r"\bexport(s)?\b",
    r"\bwall street\b",
    r"\bs&p 500\b",
    r"\bnasdaq\b",
    r"\bdow jones\b",
    r"\bdividend(s)?\b",
    r"\byield(s)?\b",
    r"\bportfolio\b",
    r"\basset(s)?\b",
    r"\bwealth\b",
    r"\bbillion\b",
    r"\bmillion\b",
    r"\bprofit(s)?\b",
    r"\bloss(es)?\b",
    r"\brevenue(s)?\b",
    r"\bearnings\b",
    r"\bipo\b",
    r"\bmerger\b",
    r"\bacquisit(ion|e)\b",
    r"\bvolatil(e|ity)\b",
    r"\bliquid(ity|ate)\b",
    r"\bhedge\b",
    r"\bbubble\b",
    r"\bcrash\b",
    r"\brally\b",
    r"\bdownturn\b",
    r"\bupturn\b",
    r"\boutlook\b",
]

PATTERNS = [re.compile(kw, re.IGNORECASE) for kw in ECONOMIC_KEYWORDS]


def is_relevant(text: str, min_matches: int = 1) -> bool:
    if not text:
        return False
    matches = sum(1 for p in PATTERNS if p.search(text))
    return matches >= min_matches
